@rootURl = http://localhost:8000

#API list

### Check server status

GET {{rootURl}}


### Auth API


### post new user
POST {{rootURl}}/api/v1/auth/register
Content-Type: application/json

{
    "fName": "Dinesh",
    "lName": "Budhathoki",
    "phone": "123456",
    "email": "physmarika@gmail.com",
    "password": "123"
   
}


### post to activate user
POST {{rootURl}}/api/v1/auth/activate-user
Content-Type: application/json

{
    "sessionId":"","t":"5111a797-05e5-4565-a8f3-7c5"
}
### login user
POST {{rootURl}}/api/v1/auth/login
Content-Type: application/json

{
    "email":"physmarika@gmail.com",
    "password":"Gaighat123@"
}

### get user profile
GET {{rootURl}}/api/v1/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBoeXNtYXJpa2FAZ21haWwuY29tIiwiaWF0IjoxNzM3MzgxMTM1LCJleHAiOjE3MzczODIwMzV9.Wcwct9NytgCGbTZRByX8yTwg4cwxJrAnVCgd1rsti38